import setuptools
import os
from setuptools import setup, find_packages

setup(name='yabibe',
    version='0.2',
    description='Yabi Backend',
    long_description='Yabi back end service',
    author='Centre for Comparative Genomics',
    author_email='web@ccg.murdoch.edu.au',
    packages=['yabibe',
              'yabibe.conf',
              'yabibe.connectors',
              'yabibe.connectors.ex',
              'yabibe.connectors.fs',
              'yabibe.log',
              'yabibe.reactor',
              'yabibe.server',
              'yabibe.server.resources',
              'yabibe.server.resources.ex',
              'yabibe.server.resources.fs',
              'yabibe.server.resources.TaskManager',
              'yabibe.utils',
              'yabibe.utils.pexpect',
              'yabibe.utils.protocol',
              'yabibe.utils.protocol.globus',
              'yabibe.utils.protocol.s3',
              'yabibe.utils.protocol.ssh'
              ],
    package_data={'yabibe': ['conf/*.conf']},
    zip_safe=False,
    scripts=['scripts/yabibe'],
    install_requires=[
        'pyOpenSSL',
        'pycrypto',
        'paramiko',
        'Mako',
        'MarkupSafe',
        'TwistedWeb2==1.0.0',
        'setproctitle',
        'wsgiref',
        'zope.interface',
        'gevent',
        'greenlet',
        'psutil',
        'boto',
        'grequests',
    ],
    dependency_links = [
          "http://repo.ccgapps.com.au",
          "https://twisted-web2.googlecode.com/files/TwistedWeb2-1.0.0.tar.gz?"    # see: http://stackoverflow.com/questions/2653410/project-hosting-on-google-code-files-are-cached
    ],      
)
